version: '3'

services:
    web:
        image: blazor-wb
        container_name: blazor-wb
        build: visualbam/withbruce-project-web
        ports:
            - "8080:80"
    caddy:
        image: caddy:latest
        container_name: caddy-wb
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config
    db:
        image: mongo
        container_name: mongodb-wb
        environment:
            - PUID=1000
            - PGID=1000
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
volumes:
    mongodb:
        external: true
    caddy_data:
        external: true
    caddy_config: