version: 2.1

orbs:
  docker: circleci/docker@2.2.0

executors:
  docker:
    environment:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    docker:
      - image: docker:stable

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    executor: docker
    steps:
      - checkout      
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build and test
          command: |
            dotnet build
            dotnet test
      - run:
          name: Install Docker Compose
          environment:
              COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Publish and create Docker image
          command: |
            dotnet publish -c Release -o out
            docker-compose build -t withbruce-project .
