version: 2.1

jobs:
  build:
    docker:
      - image: circleci/dotnet:latest
    environment:
      DOCKER_HUB_USERNAME: ${DOCKER_HUB_USERNAME}
      DOCKER_HUB_PASSWORD: ${DOCKER_HUB_PASSWORD}
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-deps-{{ checksum "project.assets.json" }}
            - dotnet-deps-
      - run:
          name: Restore dependencies
          command: dotnet restore
      - save_cache:
          paths:
            - ".nuget"
          key: dotnet-deps-{{ checksum "project.assets.json" }}
      - run:
          name: Build and test
          command: |
            dotnet build
            dotnet test
      - run:
          name: Deploy to staging
          command: |
            docker-compose up -d --build
