version: 2.1

orbs:
  docker: circleci/docker@2.2.0

executors:
  docker:
    environment:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    docker:
      - image: docker:stable

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
          
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build and test
          command: |
            dotnet build
            dotnet test
      - run:
          name: Set up Docker Compose
          command: |
            apt-get update
            apt-get install -y docker.io
            apt-get install -y python3 python3-pip
            pip3 install docker-compose
            service docker start
      - run:
          name: Publish and create Docker image
          command: |
            dotnet publish -c Release -o out
            docker build -t withbruce-project .
      - run:
          name: Deploy to staging
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker-compose -f docker-compose.yml up -d
